# jenkins-casc.yaml (Simplified and Corrected)

# --- CREDENTIALS ---
credentials:
  # The system block is correct for defining a Username/Password credential
  system:
    domainCredentials:
      - credentials:
          - usernamePassword:
              id: "4caed40b-5d9a-401c-bbb9-2fd5673b07ee"
              password: "{AQAAABAAAAAwNIuG+cY1RgrbUzqJX69hFdZp8su5y117Wvq7nhrl6RnbSDMB+kGKYflEUvi9xvplzngCos3q+VdBvzyAkraPQA==}"
              scope: GLOBAL
              username: "mapel88"
        domain:
          name: "global"
# --- JENKINS CORE CONFIGURATION ---
jenkins:
  # Security Realm and Authorization
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "Admin"
          name: "Maayan"
          password: '#jbcrypt:$2a$10$K2t3Bqw4hR.RIZfPQd9zeekhTHa48PDH3HXAmDpWfjj/5OcJIuj.2'
          properties:
            - "favorite"
            - mailer:
                emailAddress: "mapelboim@gmail.com"
            - "apiToken"
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false

  # Docker Cloud Configuration (Agents)
  clouds:
    - docker:
        dockerApi:
          connectTimeout: 60
          dockerHost:
            uri: "unix:///var/run/docker.sock"
          readTimeout: 60
        name: "docker-agents"
        templates:
          - connector: "attach"
            dockerTemplateBase:
              # Capabilities needed for NIDS/networking tests
              capabilitiesToAdd:
                - "NET_ADMIN"
                - "NET_RAW"
              image: "ubuntu-agent:latest"
            labelString: "ubuntu-agent"
            pullStrategy: PULL_NEVER
            remoteFs: "/jenkins-workspace"
            removeVolumes: true
          - connector: "attach"
            dockerTemplateBase:
              image: "rhel-agent:latest"
              privileged: true # Required for sysctl/kernel changes
            labelString: "rhel-agent"
            mode: EXCLUSIVE
            pullStrategy: PULL_NEVER
            remoteFs: "/jenkins-workspace"
            removeVolumes: true # Added for consistency

  # Core Settings
  numExecutors: 2
  slaveAgentPort: 50000
  quietPeriod: 5
  markupFormatter: "plainText" # Should be safe since it's the default/basic
  
# --- TOOLS ---
tool:
  git:
    installations:
      - home: "git" # Assumes 'git' is available on PATH of controller or agent (it is in your Dockerfile)
        name: "Default"

# --- UNCLASSIFIED (Cleaned) ---
unclassified:
  location:
    adminAddress: "mapelboim@gmail.com"
    url: "http://localhost:8080/"

# --- JOB DSL DEFINITION ---
jobs:
  - file: /usr/share/jenkins/ref/jobs/nids-pipeline.groovy