
services:
  jenkins-master:
    build:
      context: ./jenkins/master
    container_name: jenkins-master
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    networks:
      - jenkins-net
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

networks:
  jenkins-net:
    name: jenkins-net

volumes:
  jenkins_home:
    name: jenkins_home
